reload:
set_preset_temperature:
  target:
    entity:
      domain: climate
      supported_features:
        - climate.ClimateEntityFeature.PRESET_MODE
        - climate.ClimateEntityFeature.TARGET_TEMPERATURE
  fields:
    preset_mode:
      required: true
      example: "away"
      selector:
        text:
    temperature:
      required: true
      example: "22"
      selector:
        number:
          min: 0
          max: 250
          step: 0.1
          mode: box
reset_preset_temperature:
  target:
    entity:
      domain: climate
      supported_features:
        - climate.ClimateEntityFeature.PRESET_MODE
        - climate.ClimateEntityFeature.TARGET_TEMPERATURE
  fields:
    preset_mode:
      required: false
      example: "away"
      selector:
        text:
set_tolerance:
  target:
    entity:
      domain: climate
      supported_features:
        - climate.ClimateEntityFeature.TARGET_TEMPERATURE
  fields:
    cold_tolerance:
      required: false
      example: "0.1"
      selector:
        number:
          min: 0
          max: 99
          step: 0.1
          mode: box
    hot_tolerance:
      required: false
      example: "0.1"
      selector:
        number:
          min: 0
          max: 99
          step: 0.1
          mode: box
